// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// User actions
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';
export const PROVIDER_LOGIN_SUCCESS = 'PROVIDER_LOGIN_SUCCESS';

export const NOTIFICATION_ADDED_SUCCESS = 'NOTIFICATION_ADDED_SUCCESS';
export const NOTIFICATION_REMOVED_SUCCESS = 'NOTIFICATION_REMOVED_SUCCESS';

export default {
    BEGIN_AJAX_CALL,
    AJAX_CALL_ERROR,
    AUTH_INITIALIZATION_DONE,
    AUTH_LOGGED_IN_SUCCESS,
    AUTH_LOGGED_OUT_SUCCESS,
    USER_CREATED_SUCCESS,
    USER_LOADED_SUCCESS,
    USER_IS_ADMIN_SUCCESS,
    PROVIDER_LOGIN_SUCCESS,
    NOTIFICATION_ADDED_SUCCESS,
    NOTIFICATION_REMOVED_SUCCESS,
};