export default {
  apiKey: 'PUT_FIREBASE_API_KEY_HERE',
  authDomain: 'PUT_FIREBASE_AUTH_DOMAIN_HERE',
  databaseURL: 'PUT_FIREBASE_DATABASE_URL_HERE',
  storageBucket: 'PUT_FIREBASE_STORAGE_BUCKET_HERE',
  messagingSenderId: 'PUT_FIREBASE_MESSAGING_SENDER_ID_HERE',
};
